In [1]:
import numpy as np
import pandas as pd

In [2]:
scores = np.random.randint(40, 61, 10)

In [3]:
scores

array([48, 53, 59, 60, 59, 57, 50, 46, 48, 59])

In [4]:
months = ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April', 'May', 'June']

In [5]:
s = pd.Series(data=scores, index=months, dtype=np.int8)
s

September    48
October      53
November     59
December     60
January      59
February     57
March        50
April        46
May          48
June         59
dtype: int8

In [6]:
avg = s.mean()

In [7]:
print(avg)

53.9


In [11]:
s_new = s - s.mean() + 80

In [12]:
s_new

September    74.1
October      79.1
November     85.1
December     86.1
January      85.1
February     83.1
March        76.1
April        72.1
May          74.1
June         85.1
dtype: float64

In [13]:
s_new.mean()

np.float64(80.0)

In [14]:
np.random.rand(10)

array([0.34608792, 0.53104806, 0.3101646 , 0.78201487, 0.39568999,
       0.32213244, 0.86401559, 0.60492101, 0.25720646, 0.5397774 ])

In [15]:
np.random.rand(10, 2)

array([[0.79479018, 0.56024895],
       [0.73594737, 0.37644235],
       [0.22838501, 0.55760142],
       [0.14147638, 0.02936204],
       [0.54921831, 0.43890877],
       [0.91407584, 0.96344328],
       [0.91528948, 0.33830374],
       [0.99065238, 0.34951177],
       [0.63127124, 0.7137896 ],
       [0.19546801, 0.16624443]])

In [19]:
np.random.randint(40, 61, (10, 2, 3))

array([[[57, 49, 44],
        [53, 46, 49]],

       [[59, 57, 58],
        [40, 48, 46]],

       [[54, 45, 49],
        [52, 54, 51]],

       [[55, 48, 51],
        [51, 58, 40]],

       [[47, 42, 55],
        [58, 43, 49]],

       [[48, 56, 44],
        [52, 52, 53]],

       [[45, 42, 49],
        [49, 50, 41]],

       [[50, 52, 59],
        [59, 52, 42]],

       [[60, 46, 49],
        [44, 46, 46]],

       [[57, 58, 58],
        [55, 49, 42]]])

In [20]:
g = np.random.default_rng(0)

In [21]:
g.integers(40, 61, (10, 2))

array([[57, 53],
       [50, 45],
       [46, 40],
       [41, 40],
       [43, 57],
       [53, 59],
       [50, 52],
       [60, 55],
       [53, 51],
       [51, 59]])

In [23]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s1

a    10
b    20
c    30
dtype: int64

In [24]:
s2 = pd.Series([1, 2, 3], index=['aa', 'b', 'd'])
s2

aa    1
b     2
d     3
dtype: int64

In [25]:
s1 + s2

a      NaN
aa     NaN
b     22.0
c      NaN
d      NaN
dtype: float64

In [26]:
# 2.1

In [27]:
s = pd.Series(data=g.integers(40, 61, 10), index=months, dtype=np.int8)
s

September    45
October      57
November     54
December     40
January      48
February     58
March        51
April        40
May          56
June         55
dtype: int8

In [28]:
s.mean()

np.float64(50.4)

In [29]:
avg = s.mean()
std = s.std()

In [30]:
print(f'{avg} {std}')

50.4 6.818276093624318


In [31]:
def get_grade_calc(avg, std):
    def get_grade(score):
        if score < avg - std:
            return 'D'
        elif avg - std <= score < avg:
            return 'C'
        elif avg <= score < avg + std:
            return 'B'
        else:
            return 'A'
    
    return get_grade 

In [32]:
s_new = s.apply(get_grade_calc(avg, std))
s_new

September    C
October      B
November     B
December     D
January      C
February     A
March        B
April        D
May          B
June         B
dtype: object

In [33]:
# 2.2

In [34]:
s[(s > s.mean() + 2 * s.std()) | (s < s.mean() - 2 * s.std())]

Series([], dtype: int8)

In [35]:
# 2.3

In [36]:
print(f'{s.mean()} vs {s.median()}')

50.4 vs 52.5
