In [1]:
import numpy as np
import pandas as pd

In [2]:
# Exercises

In [4]:
week_1 = pd.read_csv('restaurant/week_1_sales.csv')
week_1

,Customer ID,Food ID
0,537,9
1,97,4
2,658,1
3,202,2
4,155,9
...,...,...
245,413,9
246,926,6
247,134,3
248,396,6


In [5]:
week_2 = pd.read_csv('restaurant/week_2_sales.csv')
week_2

,Customer ID,Food ID
0,688,10
1,813,7
2,495,10
3,189,5
4,267,3
...,...,...
245,783,10
246,556,10
247,547,9
248,252,9


In [6]:
customers = pd.read_csv('restaurant/customers.csv')
customers

,ID,First Name,Last Name,Gender,Company,Occupation
0,1,Joseph,Perkins,Male,Dynazzy,Community Outreach Specialist
1,2,Jennifer,Alvarez,Female,DabZ,Senior Quality Engineer
2,3,Roger,Black,Male,Tagfeed,Account Executive
3,4,Steven,Evans,Male,Fatz,Registered Nurse
4,5,Judy,Morrison,Female,Demivee,Legal Assistant
...,...,...,...,...,...,...
995,996,Debra,Garcia,Female,Dazzlesphere,Structural Engineer
996,997,Douglas,Bishop,Male,Livepath,Developer I
997,998,Frank,Franklin,Male,Brainverse,Nurse Practicioner
998,999,Jessica,Burns,Female,Babbleblab,Financial Advisor


In [7]:
customers.nunique()

ID            1000
First Name     198
Last Name      248
Gender           2
Company        353
Occupation     181
dtype: int64

In [8]:
customers = customers.set_index(keys=['ID']).sort_index()

In [9]:
customers

,First Name,Last Name,Gender,Company,Occupation
ID,,,,,
1,Joseph,Perkins,Male,Dynazzy,Community Outreach Specialist
2,Jennifer,Alvarez,Female,DabZ,Senior Quality Engineer
3,Roger,Black,Male,Tagfeed,Account Executive
4,Steven,Evans,Male,Fatz,Registered Nurse
5,Judy,Morrison,Female,Demivee,Legal Assistant
...,...,...,...,...,...
996,Debra,Garcia,Female,Dazzlesphere,Structural Engineer
997,Douglas,Bishop,Male,Livepath,Developer I
998,Frank,Franklin,Male,Brainverse,Nurse Practicioner


In [10]:
foods = pd.read_csv('restaurant/foods.csv')
foods

,Food ID,Food Item,Price
0,1,Sushi,3.99
1,2,Burrito,9.99
2,3,Taco,2.99
3,4,Quesadilla,4.25
4,5,Pizza,2.49
5,6,Pasta,13.99
6,7,Steak,24.99
7,8,Salad,11.25
8,9,Donut,0.99
9,10,Drink,1.75


In [12]:
foods.nunique()

Food ID      10
Food Item    10
Price        10
dtype: int64

In [15]:
foods = foods.set_index(keys=['Food ID']).sort_index()
foods

,Food Item,Price
Food ID,,
1,Sushi,3.99
2,Burrito,9.99
3,Taco,2.99
4,Quesadilla,4.25
5,Pizza,2.49
6,Pasta,13.99
7,Steak,24.99
8,Salad,11.25
9,Donut,0.99


In [16]:
# 1

In [18]:
weeks = pd.concat(objs=[week_1, week_2], keys=['Week 1', 'Week 2'])
weeks

Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [19]:
# 2

In [24]:
weeks.loc['Week 1']

,Customer ID,Food ID
0,537,9
1,97,4
2,658,1
3,202,2
4,155,9
...,...,...
245,413,9
246,926,6
247,134,3
248,396,6


In [25]:
weeks.loc['Week 2']

,Customer ID,Food ID
0,688,10
1,813,7
2,495,10
3,189,5
4,267,3
...,...,...
245,783,10
246,556,10
247,547,9
248,252,9


In [31]:
customers_both_weeks = weeks.loc['Week 1'].merge(weeks.loc['Week 2'], how='inner', on=['Customer ID'])['Customer ID'].unique()
customers_both_weeks

array([537, 155, 503, 550, 101,  75,  77, 628, 798, 462, 304, 189, 799,
        30, 249, 677, 741, 540, 819, 937, 233,  21, 459, 816, 761,  80,
       479, 922, 909, 919, 574,  45, 529, 673, 310, 867, 968, 482, 163,
       321, 783, 578, 520, 945, 343, 621])

In [32]:
# 3

In [33]:
customers_both_weeks_and_dishes = weeks.loc['Week 1'].merge(weeks.loc['Week 2'], how='inner', on=['Customer ID', 'Food ID'])['Customer ID'].unique()
customers_both_weeks_and_dishes

array([304, 540, 937, 233,  21, 922, 578])

In [44]:
# 4

In [41]:
customers_one_week_only = weeks.loc[('Week 1',)].merge(weeks.loc[('Week 2',)], how='outer', on=['Customer ID'], indicator=True)
customers_one_week_only = customers_one_week_only[customers_one_week_only['_merge'].isin(['left_only', 'right_only'])]['Customer ID'].unique()
customers_one_week_only

array([   3,    8,   10,   13,   20,   24,   26,   27,   35,   38,   39,
         46,   47,   51,   53,   54,   55,   56,   62,   63,   64,   67,
         68,   70,   71,   73,   74,   78,   81,   91,   92,   93,   97,
         98,  100,  107,  108,  110,  111,  114,  117,  121,  122,  123,
        127,  131,  132,  134,  136,  138,  140,  143,  144,  145,  147,
        148,  149,  151,  156,  159,  160,  167,  170,  171,  174,  175,
        184,  186,  188,  190,  191,  193,  198,  202,  203,  204,  208,
        211,  213,  222,  225,  226,  234,  236,  239,  240,  244,  250,
        251,  252,  253,  257,  259,  260,  263,  264,  267,  271,  272,
        274,  275,  276,  277,  281,  282,  287,  288,  290,  296,  303,
        305,  307,  312,  313,  315,  319,  323,  325,  327,  329,  331,
        332,  338,  341,  346,  348,  351,  352,  357,  358,  359,  361,
        363,  365,  367,  368,  372,  374,  379,  380,  381,  385,  386,
        393,  396,  397,  398,  399,  406,  410,  4

In [42]:
len(customers_one_week_only)

353

In [45]:
# 5

In [48]:
weeks_with_customers = weeks.merge(customers, how='left', left_on=['Customer ID'], right_index=True)
weeks_with_customers

Customer ID  Food ID First Name  Last Name  Gender       Company  \
Week 1 0            537        9     Cheryl    Carroll  Female      Zoombeat   
       1             97        4     Amanda    Watkins  Female           Ozu   
       2            658        1    Patrick       Webb    Male     Browsebug   
       3            202        2      Louis   Campbell    Male     Rhynoodle   
       4            155        9    Carolyn       Diaz  Female      Gigazoom   
...                 ...      ...        ...        ...     ...           ...   
Week 2 245          783       10    Phyllis      Meyer  Female        Voolia   
       246          556       10     Samuel     Bailey    Male        Oyoloo   
       247          547        9       Tina    Watkins  Female  Thoughtstorm   
       248          252        9    Douglas     Powell    Male       Jetwire   
       249          249        6    Anthony  Carpenter    Male    Shuffletag   

                               Occupation  
Week 1 0                 Registered Nurse  
       1              Account Coordinator  
       2    Community Outreach Specialist  
       3       Account Representative III  
       4       Database Administrator III  
...                                   ...  
Week 2 245    Information Systems Manager  
       246                          Nurse  
       247                  Accountant II  
       248                   Geologist IV  
       249                 Health Coach I  

[500 rows x 7 columns]

In [50]:
weeks_with_customers.groupby(by=['Customer ID']).size().sort_values(ascending=False)

Customer ID
77      5
495     4
343     4
909     3
253     3
       ..
363     1
361     1
359     1
358     1
1000    1
Length: 399, dtype: int64

In [51]:
weeks_with_customers[weeks_with_customers['Customer ID'] == 77]

Customer ID  Food ID First Name Last Name  Gender  Company  \
Week 1 35            77        1       Lori   Edwards  Female  Dabvine   
       129           77        9       Lori   Edwards  Female  Dabvine   
       144           77        2       Lori   Edwards  Female  Dabvine   
       227           77        9       Lori   Edwards  Female  Dabvine   
Week 2 162           77        7       Lori   Edwards  Female  Dabvine   

                      Occupation  
Week 1 35   Sales Representative  
       129  Sales Representative  
       144  Sales Representative  
       227  Sales Representative  
Week 2 162  Sales Representative