In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 2, 3, 'a'])

In [3]:
s

0    1
1    2
2    3
3    a
dtype: object

In [4]:
s = pd.Series([1, 2, 3, 4, 5])

In [5]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series()

Series([], dtype: object)

In [7]:
string_list = ['a', 'b', 'c', 'd', 'e']

In [8]:
s = pd.Series(string_list)

In [9]:
s

0    a
1    b
2    c
3    d
4    e
dtype: object

In [10]:
s = pd.Series(data=string_list)

In [11]:
s

0    a
1    b
2    c
3    d
4    e
dtype: object

In [12]:
index_list = ['a', 'b', 'c', 'd', 'e']

In [13]:
s = pd.Series(data=string_list, index=index_list)

In [14]:
s

a    a
b    b
c    c
d    d
e    e
dtype: object

In [15]:
s['a']

'a'

In [16]:
s.a

'a'

In [17]:
s.d

'd'

In [18]:
index_list = ['aa', 'bb', 'cc', 'dd', 'ee']

In [19]:
s = pd.Series(data=string_list, index=index_list)

In [20]:
s

aa    a
bb    b
cc    c
dd    d
ee    e
dtype: object

In [21]:
s['aa']

'a'

In [22]:
s.aa

'a'

In [23]:
s[0]

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3966/243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


'a'

In [24]:
s.iloc[0]

'a'

In [25]:
index_list = ['aa', 'aa', 'bb', 'bb', 'cc']

In [26]:
s = pd.Series(index=index_list, data=string_list)
s

aa    a
aa    b
bb    c
bb    d
cc    e
dtype: object

In [27]:
s['aa']

aa    a
aa    b
dtype: object

In [28]:
s = pd.Series([True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [29]:
s = pd.Series([1, 2, 3, 4, 5], dtype=np.float64)
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [30]:
temperatures = [15, 12, 8, 14, np.nan, 10, 6, 2]

In [31]:
s = pd.Series(data=temperatures)
s

0    15.0
1    12.0
2     8.0
3    14.0
4     NaN
5    10.0
6     6.0
7     2.0
dtype: float64

In [32]:
simple_dict = {'a':1.5, 'b':2, 'c':3}
s = pd.Series(data=simple_dict)
s

a    1.5
b    2.0
c    3.0
dtype: float64

In [33]:
simple_tuple = (1, 2, 3, 4, 5)
s = pd.Series(data=simple_tuple)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [34]:
complex_tuple = ((1, 2, 3), (4, 5, 6), (7, 8, 9))
s = pd.Series(data=complex_tuple)
s

0    (1, 2, 3)
1    (4, 5, 6)
2    (7, 8, 9)
dtype: object

In [35]:
simple_set = {'a', 'z', 'e', 'l'}

In [36]:
simple_set

{'a', 'e', 'l', 'z'}

In [37]:
s = pd.Series(data=simple_set)

TypeError: 'set' type is unordered

In [38]:
s = pd.Series(data=sorted(list(simple_set)))
s

0    a
1    e
2    l
3    z
dtype: object

In [39]:
rand_ints = np.random.randint(1, 101, 10)
rand_ints

array([49, 75,  9, 66, 44, 92, 81, 47, 45, 11])

In [40]:
s = pd.Series(data=rand_ints)
s

0    49
1    75
2     9
3    66
4    44
5    92
6    81
7    47
8    45
9    11
dtype: int64

In [41]:
s.values

array([49, 75,  9, 66, 44, 92, 81, 47, 45, 11])

In [42]:
s.index

RangeIndex(start=0, stop=10, step=1)

In [43]:
values_list = [1, 2, 3, 4, 5]
index_list = ['a', 'b', 'c', 'd', 'e']

In [44]:
s = pd.Series(data=values_list, index=index_list)

In [45]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [46]:
s.values

array([1, 2, 3, 4, 5])

In [47]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [48]:
type(s.values)

numpy.ndarray

In [49]:
type(s.index)

pandas.core.indexes.base.Index

In [50]:
s.dtype

dtype('int64')

In [51]:
s.size

5

In [52]:
s.shape

(5,)

In [53]:
len(s)

5

In [54]:
s.is_unique

True

In [55]:
s.is_monotonic_increasing

True

In [56]:
s.is_monotonic_decreasing

False

In [57]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [58]:
s['b'] = np.nan

In [59]:
s

a    1.0
b    NaN
c    3.0
d    4.0
e    5.0
dtype: float64

In [60]:
s.is_unique

True

In [61]:
s['c'] = np.nan

In [62]:
s

a    1.0
b    NaN
c    NaN
d    4.0
e    5.0
dtype: float64

In [63]:
s.is_unique

False

In [64]:
values = range(0, 501, 5)
nums = pd.Series(data=values)

In [65]:
nums

0        0
1        5
2       10
3       15
4       20
      ... 
96     480
97     485
98     490
99     495
100    500
Length: 101, dtype: int64

In [66]:
nums.head(3)

0     0
1     5
2    10
dtype: int64

In [67]:
nums.tail(10)

91     455
92     460
93     465
94     470
95     475
96     480
97     485
98     490
99     495
100    500
dtype: int64

In [68]:
nums

0        0
1        5
2       10
3       15
4       20
      ... 
96     480
97     485
98     490
99     495
100    500
Length: 101, dtype: int64

In [69]:
numbers = pd.Series([1, 2, 3, np.nan, 4, 5])
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [70]:
numbers.count()

np.int64(5)

In [71]:
len(numbers)

6

In [72]:
numbers.sum()

np.float64(15.0)

In [73]:
numbers.sum(skipna=False)

np.float64(nan)

In [74]:
numbers.sum(min_count=6)

np.float64(nan)

In [75]:
numbers.sum(min_count=5)

np.float64(15.0)

In [76]:
numbers.product()

np.float64(120.0)

In [77]:
numbers.product(skipna=False)

np.float64(nan)

In [78]:
numbers.cumsum()

0     1.0
1     3.0
2     6.0
3     NaN
4    10.0
5    15.0
dtype: float64

In [79]:
numbers.cumsum(skipna=False)

0    1.0
1    3.0
2    6.0
3    NaN
4    NaN
5    NaN
dtype: float64

In [80]:
numbers.pct_change()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3966/527026991.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change()


0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [81]:
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [82]:
(4 - 3)/ 3

0.3333333333333333

In [83]:
(5 - 4) / 4

0.25

In [84]:
numbers.pct_change(fill_method='bfill')

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3966/629865841.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change(fill_method='bfill')


0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.000000
5    0.250000
dtype: float64

In [85]:
numbers.fillna(method='ffill').pct_change()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3966/1338011009.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  numbers.fillna(method='ffill').pct_change()


0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [87]:
numbers.ffill().pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [88]:
numbers.bfill().pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.000000
5    0.250000
dtype: float64

In [89]:
numbers.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    4.0
5    5.0
dtype: float64

In [90]:
numbers.mean()

np.float64(3.0)

In [91]:
numbers.median()

3.0

In [92]:
numbers.std()

1.5811388300841898

In [93]:
numbers.max()

5.0

In [94]:
numbers.min()

1.0

In [95]:
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [96]:
pd.Series(['a', 'z', 'h']).max()

'z'

In [97]:
pd.Series(['a', 'z', 'h']).mean()

TypeError: Could not convert string 'azh' to numeric

In [98]:
numbers.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [102]:
numbers.sample(3)

3    NaN
0    1.0
4    4.0
dtype: float64

In [103]:
numbers.unique()

array([ 1.,  2.,  3., nan,  4.,  5.])

In [104]:
numbers.nunique()

5

In [105]:
len(numbers)

6

In [106]:
numbers.count()

np.int64(5)

In [107]:
nums = numbers.fillna(0)

In [108]:
nums

0    1.0
1    2.0
2    3.0
3    0.0
4    4.0
5    5.0
dtype: float64

In [110]:
nums = nums.astype(np.int8)

In [111]:
nums

0    1
1    2
2    3
3    0
4    4
5    5
dtype: int8

In [112]:
numbers.info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: None
Non-Null Count  Dtype  
--------------  -----  
5 non-null      float64
dtypes: float64(1)
memory usage: 180.0 bytes


In [118]:
nums.memory_usage()

138

In [119]:
numbers.memory_usage()

180

In [120]:
s = pd.Series(data=[5, np.nan, 15], index=['a', 'b', 'c'])

In [121]:
s

a     5.0
b     NaN
c    15.0
dtype: float64

In [122]:
s +3

a     8.0
b     NaN
c    18.0
dtype: float64

In [123]:
s // 4

a    1.0
b    NaN
c    3.0
dtype: float64

In [124]:
s % 3

a    2.0
b    NaN
c    0.0
dtype: float64

In [125]:
s1 = pd.Series([1, 2,  np.nan, 3])
s2 = pd.Series([2, 2, np.nan, 3])

In [126]:
s1 == s2

0    False
1     True
2    False
3     True
dtype: bool

In [127]:
s1 != s2

0     True
1    False
2     True
3    False
dtype: bool

In [128]:
s1 + s2

0    3.0
1    4.0
2    NaN
3    6.0
dtype: float64

In [131]:
s1 = pd.Series(data=[1, 2,  np.nan, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series(data=[2, 2, np.nan, 3], index=['a', 'b', 'f', 'd'])

In [132]:
s1 + s2

a    3.0
b    4.0
c    NaN
d    6.0
f    NaN
dtype: float64

In [133]:
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [134]:
dict(numbers)

{0: np.float64(1.0),
 1: np.float64(2.0),
 2: np.float64(3.0),
 3: np.float64(nan),
 4: np.float64(4.0),
 5: np.float64(5.0)}

In [135]:
2 in numbers

True

In [136]:
'a' in numbers

False

In [137]:
numbers = pd.Series([100, 200, 300])

In [138]:
numbers

0    100
1    200
2    300
dtype: int64

In [139]:
2 in numbers

True

In [140]:
100 in numbers

False

In [141]:
100 in numbers.values

True

In [142]:
# Exercises

In [144]:
superheroes = [
    'Batman',
    'Superman',
    'Spider-Man',
    'Iron Man',
    'Captain America',
    'Wonder Woman'
]

In [145]:
strength_levels = (100, 120, 90, 95, 110, 120)

In [146]:
len(superheroes) == len(strength_levels)

True

In [147]:
# 1

In [148]:
heroes = pd.Series(data=superheroes)
heroes

0             Batman
1           Superman
2         Spider-Man
3           Iron Man
4    Captain America
5       Wonder Woman
dtype: object

In [149]:
# 2

In [150]:
strengths = pd.Series(data=strength_levels)
strengths

0    100
1    120
2     90
3     95
4    110
5    120
dtype: int64

In [151]:
# 3

In [152]:
heroes = pd.Series(data=superheroes, index=strength_levels)
heroes

100             Batman
120           Superman
90          Spider-Man
95            Iron Man
110    Captain America
120       Wonder Woman
dtype: object

In [153]:
# 4

In [154]:
heroes.head(2)

100      Batman
120    Superman
dtype: object

In [155]:
heroes.iloc[0:1]

100    Batman
dtype: object

In [156]:
heroes.iloc[0:2]

100      Batman
120    Superman
dtype: object

In [158]:
# 5

In [159]:
heroes.tail(4)

90          Spider-Man
95            Iron Man
110    Captain America
120       Wonder Woman
dtype: object

In [162]:
heroes.iloc[-4:]

90          Spider-Man
95            Iron Man
110    Captain America
120       Wonder Woman
dtype: object

In [163]:
# 6

In [164]:
heroes.nunique()

6

In [165]:
len(heroes)

6

In [174]:
# 7

In [168]:
heroes = pd.Series(index=superheroes, data=strength_levels)
heroes

Batman             100
Superman           120
Spider-Man          90
Iron Man            95
Captain America    110
Wonder Woman       120
dtype: int64

In [168]:
heroes = pd.Series(index=superheroes, data=strength_levels)
heroes

Batman             100
Superman           120
Spider-Man          90
Iron Man            95
Captain America    110
Wonder Woman       120
dtype: int64

In [169]:
heroes.mean()

np.float64(105.83333333333333)

In [171]:
heroes.nunique()

5

In [172]:
len(heroes)

6

In [175]:
# 8

In [176]:
heroes.min()

90

In [177]:
heroes.max()

120

In [178]:
# 9

In [179]:
heroes * 2

Batman             200
Superman           240
Spider-Man         180
Iron Man           190
Captain America    220
Wonder Woman       240
dtype: int64

In [180]:
# 10

In [181]:
dict(heroes)

{'Batman': np.int64(100),
 'Superman': np.int64(120),
 'Spider-Man': np.int64(90),
 'Iron Man': np.int64(95),
 'Captain America': np.int64(110),
 'Wonder Woman': np.int64(120)}